inventory-full:
    title: "&8| &6&lINVENTORY FULL &8|"
    subtitle: "&7You cannot pickup any items"
    fadein: 10
    stay: 70
    fadeout: 20
    
messages:    
    prefix: "&a&lInventoryBlocks > &7"

    no-perms: "&7You don't have the permission"
    reload-complete: "&7Reload complete"
    
    help: "All commands: "
    help-format: "&7- &a%s &8(&r%s&8)"